# Site settings
title: Musyoka Morris blog
email: musyokamorris@gmail.com
description: "Intersection of Computer Science and Mathematics."
baseurl: ""
url: "http://musyoka-morris.github.io"
twitter_username: musyoka_mm
github_username:  musyoka-morris
linkedin_username: musyoka-mm

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge